#ifndef _SEPOL_CONSTANTS_H_
#define _SEPOL_CONSTANTS_H_

/*
 * Policy interpretation constants shared across libsepol and consumers
 * (e.g. SETools) that need stable numeric tokens without pulling in full
 * policydb, avtab, or service API headers.
 *
 * Values match the kernel / policy binary format and must stay in sync
 * with libsepol's internal policy representation.
 *
 * Public API consumers should prefer the SEPOL_-prefixed aliases below.
 * The unprefixed forms are provided for source compatibility with code
 * that also includes internal policydb headers; #ifndef guards prevent
 * redefinition conflicts.
 */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* --- Namespace-safe constants for public API consumers --- */

#define SEPOL_AVTAB_ALLOWED 0x0001
#define SEPOL_AVTAB_AUDITALLOW 0x0002
#define SEPOL_AVTAB_AUDITDENY 0x0004
#define SEPOL_AVTAB_NEVERALLOW 0x0080
#define SEPOL_AVTAB_AV \
	(SEPOL_AVTAB_ALLOWED | SEPOL_AVTAB_AUDITALLOW | SEPOL_AVTAB_AUDITDENY)
#define SEPOL_AVTAB_TRANSITION 0x0010
#define SEPOL_AVTAB_MEMBER 0x0020
#define SEPOL_AVTAB_CHANGE 0x0040
#define SEPOL_AVTAB_TYPE \
	(SEPOL_AVTAB_TRANSITION | SEPOL_AVTAB_MEMBER | SEPOL_AVTAB_CHANGE)
#define SEPOL_AVTAB_XPERMS_ALLOWED 0x0100
#define SEPOL_AVTAB_XPERMS_AUDITALLOW 0x0200
#define SEPOL_AVTAB_XPERMS_DONTAUDIT 0x0400
#define SEPOL_AVTAB_XPERMS_NEVERALLOW 0x0800
#define SEPOL_AVTAB_XPERMS                                            \
	(SEPOL_AVTAB_XPERMS_ALLOWED | SEPOL_AVTAB_XPERMS_AUDITALLOW | \
	 SEPOL_AVTAB_XPERMS_DONTAUDIT)
#define SEPOL_AVTAB_ENABLED_OLD 0x80000000
#define SEPOL_AVTAB_ENABLED 0x8000

#define SEPOL_AVTAB_XPERMS_IOCTLFUNCTION 0x01
#define SEPOL_AVTAB_XPERMS_IOCTLDRIVER 0x02
#define SEPOL_AVTAB_XPERMS_NLMSG 0x03

#define SEPOL_AVRULE_ALLOWED SEPOL_AVTAB_ALLOWED
#define SEPOL_AVRULE_AUDITALLOW SEPOL_AVTAB_AUDITALLOW
#define SEPOL_AVRULE_AUDITDENY SEPOL_AVTAB_AUDITDENY
#define SEPOL_AVRULE_DONTAUDIT 0x0008
#define SEPOL_AVRULE_NEVERALLOW SEPOL_AVTAB_NEVERALLOW
#define SEPOL_AVRULE_AV                                    \
	(SEPOL_AVRULE_ALLOWED | SEPOL_AVRULE_AUDITALLOW |  \
	 SEPOL_AVRULE_AUDITDENY | SEPOL_AVRULE_DONTAUDIT | \
	 SEPOL_AVRULE_NEVERALLOW)
#define SEPOL_AVRULE_TRANSITION SEPOL_AVTAB_TRANSITION
#define SEPOL_AVRULE_MEMBER SEPOL_AVTAB_MEMBER
#define SEPOL_AVRULE_CHANGE SEPOL_AVTAB_CHANGE
#define SEPOL_AVRULE_TYPE \
	(SEPOL_AVRULE_TRANSITION | SEPOL_AVRULE_MEMBER | SEPOL_AVRULE_CHANGE)
#define SEPOL_AVRULE_XPERMS_ALLOWED SEPOL_AVTAB_XPERMS_ALLOWED
#define SEPOL_AVRULE_XPERMS_AUDITALLOW SEPOL_AVTAB_XPERMS_AUDITALLOW
#define SEPOL_AVRULE_XPERMS_DONTAUDIT SEPOL_AVTAB_XPERMS_DONTAUDIT
#define SEPOL_AVRULE_XPERMS_NEVERALLOW SEPOL_AVTAB_XPERMS_NEVERALLOW
#define SEPOL_AVRULE_XPERMS                                             \
	(SEPOL_AVRULE_XPERMS_ALLOWED | SEPOL_AVRULE_XPERMS_AUDITALLOW | \
	 SEPOL_AVRULE_XPERMS_DONTAUDIT | SEPOL_AVRULE_XPERMS_NEVERALLOW)
#define SEPOL_AVRULE_XPERMS_IOCTLFUNCTION SEPOL_AVTAB_XPERMS_IOCTLFUNCTION
#define SEPOL_AVRULE_XPERMS_IOCTLDRIVER SEPOL_AVTAB_XPERMS_IOCTLDRIVER
#define SEPOL_AVRULE_XPERMS_NLMSG SEPOL_AVTAB_XPERMS_NLMSG

#define SEPOL_RULE_SELF (1U << 0)
#define SEPOL_RULE_NOTSELF (1U << 1)

#define SEPOL_SECURITY_FS_USE_XATTR 1
#define SEPOL_SECURITY_FS_USE_TRANS 2
#define SEPOL_SECURITY_FS_USE_TASK 3
#define SEPOL_SECURITY_FS_USE_GENFS 4
#define SEPOL_SECURITY_FS_USE_NONE 5

#define SEPOL_SYM_COMMONS 0
#define SEPOL_SYM_CLASSES 1
#define SEPOL_SYM_ROLES 2
#define SEPOL_SYM_TYPES 3
#define SEPOL_SYM_USERS 4
#define SEPOL_SYM_BOOLS 5
#define SEPOL_SYM_LEVELS 6
#define SEPOL_SYM_CATS 7
#define SEPOL_SYM_NUM 8

#define SEPOL_OCON_ISID 0
#define SEPOL_OCON_FS 1
#define SEPOL_OCON_PORT 2
#define SEPOL_OCON_NETIF 3
#define SEPOL_OCON_NODE 4
#define SEPOL_OCON_FSUSE 5
#define SEPOL_OCON_NODE6 6
#define SEPOL_OCON_IBPKEY 7
#define SEPOL_OCON_IBENDPORT 8
#define SEPOL_OCON_XEN_ISID 0
#define SEPOL_OCON_XEN_PIRQ 1
#define SEPOL_OCON_XEN_IOPORT 2
#define SEPOL_OCON_XEN_IOMEM 3
#define SEPOL_OCON_XEN_PCIDEVICE 4
#define SEPOL_OCON_XEN_DEVICETREE 5
#define SEPOL_OCON_NUM 9

#define SEPOL_EXTENDED_PERMS_LEN 8
#define SEPOL_MAX_AVTAB_HASH_BITS 20
#define SEPOL_MAX_AVTAB_HASH_BUCKETS (1 << SEPOL_MAX_AVTAB_HASH_BITS)
#define SEPOL_MAX_AVTAB_SIZE (SEPOL_MAX_AVTAB_HASH_BUCKETS << 1)

/*
 * Unprefixed forms for backward compatibility with code that mixes
 * public and internal headers.  Guarded to avoid redefinition warnings
 * when policydb/avtab.h or similar internal headers are also included.
 */

#ifndef AVTAB_ALLOWED
#define AVTAB_ALLOWED SEPOL_AVTAB_ALLOWED
#define AVTAB_AUDITALLOW SEPOL_AVTAB_AUDITALLOW
#define AVTAB_AUDITDENY SEPOL_AVTAB_AUDITDENY
#define AVTAB_NEVERALLOW SEPOL_AVTAB_NEVERALLOW
#define AVTAB_AV SEPOL_AVTAB_AV
#define AVTAB_TRANSITION SEPOL_AVTAB_TRANSITION
#define AVTAB_MEMBER SEPOL_AVTAB_MEMBER
#define AVTAB_CHANGE SEPOL_AVTAB_CHANGE
#define AVTAB_TYPE SEPOL_AVTAB_TYPE
#define AVTAB_XPERMS_ALLOWED SEPOL_AVTAB_XPERMS_ALLOWED
#define AVTAB_XPERMS_AUDITALLOW SEPOL_AVTAB_XPERMS_AUDITALLOW
#define AVTAB_XPERMS_DONTAUDIT SEPOL_AVTAB_XPERMS_DONTAUDIT
#define AVTAB_XPERMS_NEVERALLOW SEPOL_AVTAB_XPERMS_NEVERALLOW
#define AVTAB_XPERMS SEPOL_AVTAB_XPERMS
#define AVTAB_ENABLED_OLD SEPOL_AVTAB_ENABLED_OLD
#define AVTAB_ENABLED SEPOL_AVTAB_ENABLED
#define AVTAB_XPERMS_IOCTLFUNCTION SEPOL_AVTAB_XPERMS_IOCTLFUNCTION
#define AVTAB_XPERMS_IOCTLDRIVER SEPOL_AVTAB_XPERMS_IOCTLDRIVER
#define AVTAB_XPERMS_NLMSG SEPOL_AVTAB_XPERMS_NLMSG
#endif

#ifndef AVRULE_ALLOWED
#define AVRULE_ALLOWED SEPOL_AVRULE_ALLOWED
#define AVRULE_AUDITALLOW SEPOL_AVRULE_AUDITALLOW
#define AVRULE_AUDITDENY SEPOL_AVRULE_AUDITDENY
#define AVRULE_DONTAUDIT SEPOL_AVRULE_DONTAUDIT
#define AVRULE_NEVERALLOW SEPOL_AVRULE_NEVERALLOW
#define AVRULE_AV SEPOL_AVRULE_AV
#define AVRULE_TRANSITION SEPOL_AVRULE_TRANSITION
#define AVRULE_MEMBER SEPOL_AVRULE_MEMBER
#define AVRULE_CHANGE SEPOL_AVRULE_CHANGE
#define AVRULE_TYPE SEPOL_AVRULE_TYPE
#define AVRULE_XPERMS_ALLOWED SEPOL_AVRULE_XPERMS_ALLOWED
#define AVRULE_XPERMS_AUDITALLOW SEPOL_AVRULE_XPERMS_AUDITALLOW
#define AVRULE_XPERMS_DONTAUDIT SEPOL_AVRULE_XPERMS_DONTAUDIT
#define AVRULE_XPERMS_NEVERALLOW SEPOL_AVRULE_XPERMS_NEVERALLOW
#define AVRULE_XPERMS SEPOL_AVRULE_XPERMS
#define AVRULE_XPERMS_IOCTLFUNCTION SEPOL_AVRULE_XPERMS_IOCTLFUNCTION
#define AVRULE_XPERMS_IOCTLDRIVER SEPOL_AVRULE_XPERMS_IOCTLDRIVER
#define AVRULE_XPERMS_NLMSG SEPOL_AVRULE_XPERMS_NLMSG
#endif

#ifndef RULE_SELF
#define RULE_SELF SEPOL_RULE_SELF
#define RULE_NOTSELF SEPOL_RULE_NOTSELF
#endif

#ifndef SECURITY_FS_USE_XATTR
#define SECURITY_FS_USE_XATTR SEPOL_SECURITY_FS_USE_XATTR
#define SECURITY_FS_USE_TRANS SEPOL_SECURITY_FS_USE_TRANS
#define SECURITY_FS_USE_TASK SEPOL_SECURITY_FS_USE_TASK
#define SECURITY_FS_USE_GENFS SEPOL_SECURITY_FS_USE_GENFS
#define SECURITY_FS_USE_NONE SEPOL_SECURITY_FS_USE_NONE
#endif

#ifndef SYM_COMMONS
#define SYM_COMMONS SEPOL_SYM_COMMONS
#define SYM_CLASSES SEPOL_SYM_CLASSES
#define SYM_ROLES SEPOL_SYM_ROLES
#define SYM_TYPES SEPOL_SYM_TYPES
#define SYM_USERS SEPOL_SYM_USERS
#define SYM_BOOLS SEPOL_SYM_BOOLS
#define SYM_LEVELS SEPOL_SYM_LEVELS
#define SYM_CATS SEPOL_SYM_CATS
#define SYM_NUM SEPOL_SYM_NUM
#endif

#ifndef OCON_ISID
#define OCON_ISID SEPOL_OCON_ISID
#define OCON_FS SEPOL_OCON_FS
#define OCON_PORT SEPOL_OCON_PORT
#define OCON_NETIF SEPOL_OCON_NETIF
#define OCON_NODE SEPOL_OCON_NODE
#define OCON_FSUSE SEPOL_OCON_FSUSE
#define OCON_NODE6 SEPOL_OCON_NODE6
#define OCON_IBPKEY SEPOL_OCON_IBPKEY
#define OCON_IBENDPORT SEPOL_OCON_IBENDPORT
#define OCON_XEN_ISID SEPOL_OCON_XEN_ISID
#define OCON_XEN_PIRQ SEPOL_OCON_XEN_PIRQ
#define OCON_XEN_IOPORT SEPOL_OCON_XEN_IOPORT
#define OCON_XEN_IOMEM SEPOL_OCON_XEN_IOMEM
#define OCON_XEN_PCIDEVICE SEPOL_OCON_XEN_PCIDEVICE
#define OCON_XEN_DEVICETREE SEPOL_OCON_XEN_DEVICETREE
#define OCON_NUM SEPOL_OCON_NUM
#endif

#ifndef EXTENDED_PERMS_LEN
#define EXTENDED_PERMS_LEN SEPOL_EXTENDED_PERMS_LEN
#endif

#ifndef xperm_test
#define xperm_test(x, p) (1U & ((p)[(x) >> 5] >> ((x) & 0x1f)))
#define xperm_set(x, p) ((p)[(x) >> 5] |= (1U << ((x) & 0x1f)))
#define xperm_clear(x, p) ((p)[(x) >> 5] &= ~(1U << ((x) & 0x1f)))
#endif

#ifndef MAX_AVTAB_HASH_BITS
#define MAX_AVTAB_HASH_BITS SEPOL_MAX_AVTAB_HASH_BITS
#define MAX_AVTAB_HASH_BUCKETS SEPOL_MAX_AVTAB_HASH_BUCKETS
#define MAX_AVTAB_HASH_MASK (MAX_AVTAB_HASH_BUCKETS - 1)
#define MAX_AVTAB_SIZE SEPOL_MAX_AVTAB_SIZE
#endif

#ifdef __cplusplus
}
#endif

#endif /* _SEPOL_CONSTANTS_H_ */
